[project]
name = "arcos-updater"
version = "1.0.0"
description = "An updater for Arch-based distros. One button updates system packages and Flatpaks at once"
license = "GPL-3.0-only"
requires-python = ">=3.10"
authors = [
    {name = "zcharka"},
]
dependencies = [
    "PyGObject",
]

[project.urls]
Homepage = "https://github.com/zcharka/arcos-updater"
Repository = "https://github.com/zcharka/arcos-updater"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
